ALTER TABLE activities ADD COLUMN IF NOT EXISTS oc_has_app    BOOLEAN;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS oc_uses_it    BOOLEAN;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS oc_interested  BOOLEAN;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS oc_explained   BOOLEAN DEFAULT FALSE;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS oc_photo_url   TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS oc_notes       TEXT;
